// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dwn_OX0GpCmOocflkekhCdnK6Mc8hMM',
    appId: '1:1066173331667:web:99b0687c21eaaa781e3c26',
    messagingSenderId: '1066173331667',
    projectId: 'ducpeppa',
    authDomain: 'ducpeppa.firebaseapp.com',
    storageBucket: 'ducpeppa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUWJRdmmbBKGERlY0WskWNoMxlLPpyLCc',
    appId: '1:1066173331667:android:679c026cbe9f57321e3c26',
    messagingSenderId: '1066173331667',
    projectId: 'ducpeppa',
    storageBucket: 'ducpeppa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKvP_ty6lK_RiabMp_z4o0HWt1_uC65mg',
    appId: '1:1066173331667:ios:5db0bbaa6de0b4131e3c26',
    messagingSenderId: '1066173331667',
    projectId: 'ducpeppa',
    storageBucket: 'ducpeppa.firebasestorage.app',
    iosBundleId: 'com.ducky.duckyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKvP_ty6lK_RiabMp_z4o0HWt1_uC65mg',
    appId: '1:1066173331667:ios:5db0bbaa6de0b4131e3c26',
    messagingSenderId: '1066173331667',
    projectId: 'ducpeppa',
    storageBucket: 'ducpeppa.firebasestorage.app',
    iosBundleId: 'com.ducky.duckyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1dwn_OX0GpCmOocflkekhCdnK6Mc8hMM',
    appId: '1:1066173331667:web:56feec0650dc39871e3c26',
    messagingSenderId: '1066173331667',
    projectId: 'ducpeppa',
    authDomain: 'ducpeppa.firebaseapp.com',
    storageBucket: 'ducpeppa.firebasestorage.app',
  );
}
